---
# Ansible playbook for service deployment. Pulls the latest image from the
# container registry, and replaces currently running container (if exists).
- name: Setup
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3
    image: ghcr.io/tetafro/feed-bot
    tag: latest
    container: feed-bot
    dir: "~/feed-bot"
  tasks:
    - name: Create directory for docker volume
      file:
        path: "{{ dir }}"
        state: directory
        mode: "0755"

    - name: Copy config # noqa args[module]
      copy:
        src: config.yaml.vault
        dest: "{{ dir }}/config.yaml"
        decrypt: true
        mode: "0444"

    - name: Ensure data file exists
      file:
        path: "{{ dir }}/data.yaml"
        state: touch
        mode: "0666"

    - name: Pull latest image
      docker_image:
        name: "{{ image }}:{{ tag }}"
        source: pull
        force_source: true

    - name: Remove current container
      docker_container:
        name: "{{ container }}"
        state: absent

    - name: Run new container
      docker_container:
        name: "{{ container }}"
        image: "{{ image }}:{{ tag }}"
        state: started
        restart_policy: always
        volumes:
          - "{{ dir }}:/data"
        command: -config /data/config.yaml
