# Run on push, skip release tags
on:
  push:
    branches: [master]
    tags-ignore: ['*']

name: Push commits

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test ./...
      - name: Generate coverage report
        run: ./.github/workflows/codecov.sh
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run linter
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: tetafro
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: tetafro/feed-bot:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
